import { resolve } from "node:path";
import { defineConfig } from "vite";

export default defineConfig({
  base: "./",
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        mexicoSouthAfrica: resolve(__dirname, "matches/mexico-south-africa.html"),
        southKoreaCzechia: resolve(__dirname, "matches/south-korea-czechia.html"),
        canadaBosniaHerzegovina: resolve(__dirname, "matches/canada-bosnia-herzegovina.html"),
        usaParaguay: resolve(__dirname, "matches/usa-paraguay.html"),
        qatarSwitzerland: resolve(__dirname, "matches/qatar-switzerland.html"),
        brazilMorocco: resolve(__dirname, "matches/brazil-morocco.html"),
        haitiScotland: resolve(__dirname, "matches/haiti-scotland.html"),
        australiaTurkiye: resolve(__dirname, "matches/australia-turkiye.html"),
        germanyCuracao: resolve(__dirname, "matches/germany-curacao.html"),
        netherlandsJapan: resolve(__dirname, "matches/netherlands-japan.html"),
        coteDivoireEcuador: resolve(__dirname, "matches/cote-divoire-ecuador.html"),
        swedenTunisia: resolve(__dirname, "matches/sweden-tunisia.html"),
        spainCapeVerde: resolve(__dirname, "matches/spain-cape-verde.html"),
        belgiumEgypt: resolve(__dirname, "matches/belgium-egypt.html"),
        saudiArabiaUruguay: resolve(__dirname, "matches/saudi-arabia-uruguay.html"),
        iranNewZealand: resolve(__dirname, "matches/iran-new-zealand.html"),
        franceSenegal: resolve(__dirname, "matches/france-senegal.html"),
        norwayIraq: resolve(__dirname, "matches/norway-iraq.html"),
        argentinaAlgeria: resolve(__dirname, "matches/argentina-algeria.html"),
        austriaJordan: resolve(__dirname, "matches/austria-jordan.html"),
        portugalDrCongo: resolve(__dirname, "matches/portugal-dr-congo.html"),
        englandCroatia: resolve(__dirname, "matches/england-croatia.html"),
        ghanaPanama: resolve(__dirname, "matches/ghana-panama.html"),
        uzbekistanColombia: resolve(__dirname, "matches/uzbekistan-colombia.html"),
        czechiaSouthAfrica: resolve(__dirname, "matches/czechia-south-africa.html"),
        switzerlandBosniaHerzegovina: resolve(__dirname, "matches/switzerland-bosnia-herzegovina.html"),
        canadaQatar: resolve(__dirname, "matches/canada-qatar.html"),
        mexicoSouthKorea: resolve(__dirname, "matches/mexico-south-korea.html"),
        usaAustralia: resolve(__dirname, "matches/usa-australia.html"),
        scotlandMorocco: resolve(__dirname, "matches/scotland-morocco.html"),
        brazilHaiti: resolve(__dirname, "matches/brazil-haiti.html"),
        turkiyeParaguay: resolve(__dirname, "matches/turkiye-paraguay.html"),
        netherlandsSweden: resolve(__dirname, "matches/netherlands-sweden.html"),
        germanyCoteDivoire: resolve(__dirname, "matches/germany-cote-divoire.html"),
        ecuadorCuracao: resolve(__dirname, "matches/ecuador-curacao.html"),
        tunisiaJapan: resolve(__dirname, "matches/tunisia-japan.html"),
        uruguayCapeVerde: resolve(__dirname, "matches/uruguay-cape-verde.html"),
        spainSaudiArabia: resolve(__dirname, "matches/spain-saudi-arabia.html"),
        belgiumIran: resolve(__dirname, "matches/belgium-iran.html"),
        newZealandEgypt: resolve(__dirname, "matches/new-zealand-egypt.html"),
        norwaySenegal: resolve(__dirname, "matches/norway-senegal.html"),
        franceIraq: resolve(__dirname, "matches/france-iraq.html"),
        argentinaAustria: resolve(__dirname, "matches/argentina-austria.html"),
        jordanAlgeria: resolve(__dirname, "matches/jordan-algeria.html"),
        englandGhana: resolve(__dirname, "matches/england-ghana.html"),
        panamaCroatia: resolve(__dirname, "matches/panama-croatia.html"),
        portugalUzbekistan: resolve(__dirname, "matches/portugal-uzbekistan.html"),
        colombiaDrCongo: resolve(__dirname, "matches/colombia-dr-congo.html"),
        scotlandBrazil: resolve(__dirname, "matches/scotland-brazil.html"),
        moroccoHaiti: resolve(__dirname, "matches/morocco-haiti.html"),
        switzerlandCanada: resolve(__dirname, "matches/switzerland-canada.html"),
        bosniaHerzegovinaQatar: resolve(__dirname, "matches/bosnia-herzegovina-qatar.html"),
        czechiaMexico: resolve(__dirname, "matches/czechia-mexico.html"),
        southAfricaSouthKorea: resolve(__dirname, "matches/south-africa-south-korea.html")
      }
    }
  }
});